#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2017-08-22 11:56:44
# @Author  : Funuy (you@example.org)

'''
Create a submanager command to use Migrate
'''


from flask_script import Manager
from flask_migrate import Migrate,MigrateCommand
from flask_sqlalchemy import SQLAlchemy
from flask import Flask

app = Flask(__name__) 
db = SQLAlchemy(app)        #or  db = SQLAlchemy()  db.init_app(app)
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://username:password@host:port/dbname?charset=utf8'

manager = Manager(app)
migrate = Migrate(app,db)
manager.add_command('db',MigrateCommand)
  






