#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2017-08-22 11:56:44
# @Author  : Funuy (you@example.org)

'''
Create a simple command process
'''


from flask_script import Manager
from flask import Flask
app = Flask(__name__)
manager = Manager(app)
    
  
